#!/usr/bin/env python3
"""Build ui/demo/demo-runs.js from a comparison run directory.

The UI opens as a file:// page under a Content Security Policy with
connect-src 'none', so it cannot fetch a bundled dataset. The demo run ships as
a script that assigns window.MQSIM_DEMO_RUNS instead, and ui/js/mqsim-demo.js
feeds it through the same loadFiles() path a dropped file takes.

api_call events are dropped: they are 98% of the bytes and mqsim-core.js filters
them out before parsing.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "ui" / "demo" / "demo-runs.js"


def strip_api_calls(path: Path) -> str:
    kept = []
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            if json.loads(line).get("event") == "api_call":
                continue
        except json.JSONDecodeError:
            continue
        kept.append(line)
    return "\n".join(kept) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "run_dir",
        type=Path,
        help="Comparison run directory holding <policy>-metrics.ndjson files",
    )
    parser.add_argument(
        "--out", type=Path, default=OUT, help=f"Output path (default: {OUT})"
    )
    args = parser.parse_args()

    sources = sorted(args.run_dir.glob("*-metrics.ndjson"))
    if not sources:
        raise SystemExit(f"no *-metrics.ndjson under {args.run_dir}")

    runs = [{"name": p.name, "text": strip_api_calls(p)} for p in sources]

    args.out.parent.mkdir(parents=True, exist_ok=True)
    body = ",\n".join(
        f"  {{ name: {json.dumps(r['name'])}, text: {json.dumps(r['text'])} }}"
        for r in runs
    )
    args.out.write_text(
        "// Generated by scripts/build_demo_runs.py. Do not edit.\n"
        f"// Source: {args.run_dir.name}\n"
        "window.MQSIM_DEMO_RUNS = [\n" + body + "\n];\n"
    )

    total = args.out.stat().st_size
    for r in runs:
        print(f"  {r['name']:<28} {len(r['text']) / 1024:>7.0f} KiB")
    print(f"wrote {args.out} ({total / 1024:.0f} KiB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
