#!/usr/bin/env python3
"""Generate ui/metrics-spec.js from src/mqsim/metrics.json.

The UI cannot fetch the JSON — its Content Security Policy sets
connect-src 'none' — so the spec reaches the browser as a script that assigns
window.MQSIM_METRIC_SPEC. The JSON stays the single source of truth; this file
is generated, like ui/demo/demo-runs.js.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SPEC = ROOT / "src" / "mqsim" / "metrics.json"
OUT = ROOT / "ui" / "metrics-spec.js"


def main() -> int:
    spec = json.loads(SPEC.read_text())
    OUT.write_text(
        "// Generated by scripts/build_metric_spec.py from src/mqsim/metrics.json.\n"
        "// Do not edit; edit the JSON and regenerate with `make metric-spec`.\n"
        "window.MQSIM_METRIC_SPEC = " + json.dumps(spec, indent=2) + ";\n"
    )
    print(f"{len(spec)} metrics -> {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
